version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "investing_db"
      POSTGRES_USER: "investing_db"
      POSTGRES_DB: "investing_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      postgres:
        ipv4_address: 172.16.2.5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "investing_db@test.com"
      PGADMIN_DEFAULT_PASSWORD: "investing_db"
    volumes:
      - pgadmin:/var/lib/pgadmin
    expose:
      - 80
    restart: unless-stopped
    networks:
      postgres:
        ipv4_address: 172.16.2.6
    links:
      - postgres

  nginx:
    build: ./services/nginx
    container_name: db_nginx
    restart: always
    ports:
      - 5050:80
#      - 5432:5432
    networks:
      postgres:
        ipv4_address: 172.16.2.4
    links:
      - postgres

networks:
  postgres:
    driver: bridge
    ipam:
#      driver: default
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1
#    external:
#      name: postgres

volumes:
  postgres:
  pgadmin:

